from typing import Dict, NamedTuple
from operator import itemgetter
from _tabldict import ReadJsonDict

# The most influential triangles in the OEIS database.
# The ranking is based on the number of distinct sequences
# which can be generated by a fixed pool of elementary 
# transformations mapping the triangles to other sequences.

# #@


class Rank(NamedTuple):
    anum: str
    name: str
    distinct: int
    hits: int
    misses: int

def Ranking() -> Dict[int, Rank]:

    globaldict: Dict[str, Dict[str, int]] = ReadJsonDict()
    ranks: list[Rank] = []

    for name in globaldict:
        v = list(globaldict[name].values())
        a = len(v)
        d = len(set(v))
        m = len([k for k in v if k == 0])
        anum = f"A{str(v[0]):6}"
        ranks.append(Rank(anum, name, d, a - m, m))

    sorted_ranks = sorted(ranks, key=itemgetter(2), reverse=True)
    Rankings = {n: r for n, r in enumerate(sorted_ranks)}

    print("\nRanking of triangles with regard to their impact:\n")
    for n, r in Rankings.items(): 
        print(f"[{n:2}] {r.name:17} [{r.anum}]  Distinct: {r.distinct:2}, Hits: {r.hits:2}, Misses: {r.misses:2}.")

    return Rankings

''' Note that we removed 
    [11] LahInv  [A271703]  Distinct: 40, Hits: 47, Misses: 21.
    because Lah is involutory.
'''

if __name__ == "__main__":
    Ranking()

"""
Ranking of triangles with regard to their impact:

*** Premier League ***

[ 0] StirlingSet       [A48993  ]  Distinct: 53, Hits: 62, Misses:  7.
[ 1] FallingFact       [A8279   ]  Distinct: 48, Hits: 59, Misses:  8.
[ 2] BinaryPell        [A38207  ]  Distinct: 45, Hits: 55, Misses: 13.
[ 3] Lah               [A271703 ]  Distinct: 45, Hits: 54, Misses: 14.
[ 4] Lucas             [A29635  ]  Distinct: 45, Hits: 60, Misses:  6.
[ 5] StirlingCycle     [A132393 ]  Distinct: 44, Hits: 62, Misses:  6.
[ 6] Partition         [A72233  ]  Distinct: 43, Hits: 54, Misses: 15.
[ 7] CatalanInv        [A128908 ]  Distinct: 42, Hits: 48, Misses: 20.
[ 8] Fubini            [A131689 ]  Distinct: 42, Hits: 49, Misses: 16.
[ 9] Ordinals          [A2262   ]  Distinct: 40, Hits: 65, Misses:  0.
[10] Power             [A4248   ]  Distinct: 40, Hits: 49, Misses: 20.
[11] BesselInv         [A122848 ]  Distinct: 39, Hits: 48, Misses: 20.
[12] DyckPaths         [A39599  ]  Distinct: 39, Hits: 50, Misses: 18.
[13] Motzkin           [A64189  ]  Distinct: 38, Hits: 47, Misses: 21.
[14] Catalan           [A128899 ]  Distinct: 37, Hits: 43, Misses: 25.
[15] Eulerian          [A173018 ]  Distinct: 37, Hits: 55, Misses: 14.

*** Second Division ***

[16] Monotone          [A59481  ]  Distinct: 37, Hits: 51, Misses: 16.
[17] Abel              [A137452 ]  Distinct: 36, Hits: 41, Misses: 27.
[18] AbelInv           [A59297  ]  Distinct: 36, Hits: 41, Misses: 27.
[19] Laguerre          [A21009  ]  Distinct: 36, Hits: 43, Misses: 25.
[20] Narayana          [A90181  ]  Distinct: 36, Hits: 54, Misses: 15.
[21] Schroeder         [A122538 ]  Distinct: 36, Hits: 44, Misses: 24.
[22] Bessel            [A132062 ]  Distinct: 35, Hits: 41, Misses: 27.
[23] BinomialBell      [A56857  ]  Distinct: 35, Hits: 41, Misses: 27.
[24] Divisibility      [A113704 ]  Distinct: 35, Hits: 57, Misses: 12.
[25] CatalanPaths      [A53121  ]  Distinct: 34, Hits: 51, Misses: 17.
[26] ChebyshevS        [A168561 ]  Distinct: 34, Hits: 48, Misses: 20.
[27] OrderedCycle      [A225479 ]  Distinct: 34, Hits: 38, Misses: 26.
[28] Nicomachus        [A36561  ]  Distinct: 34, Hits: 41, Misses: 23.
[29] BinomialCatalan   [A98474  ]  Distinct: 33, Hits: 38, Misses: 29.
[30] Rencontres        [A8290   ]  Distinct: 32, Hits: 42, Misses: 26.
[31] LeibnizTable      [A94053  ]  Distinct: 32, Hits: 51, Misses: 13.
[32] LucasInv          [A112857 ]  Distinct: 32, Hits: 42, Misses: 29.

# Efficiency

To give an idea of the performance of the library, we provide the following table. 
It shows the time required to calculate the first 100 rows of each triangle 
(which corresponds to the calculation of the first 5050 terms).

                     Abel 0.0052 sec
                    Andre 0.0320 sec
                   Baxter 0.0110 sec
                     Bell 0.0037 sec
                   Bessel 0.0020 sec
                  Bessel2 0.0021 sec
               BinaryPell 0.0020 sec
                 Binomial 0.0005 sec
             BinomialBell 0.0033 sec
          BinomialCatalan 0.0079 sec
             BinomialPell 0.0034 sec
         BinomialDiffPell 0.0067 sec
                  Catalan 0.0026 sec
             CatalanPaths 0.0049 sec
             CentralCycle 0.0023 sec
               CentralSet 0.0029 sec
                   Chains 0.0062 sec
                 Charlier 0.0054 sec
               ChebyshevS 0.0029 sec
               ChebyshevT 0.0015 sec
               ChebyshevU 0.0032 sec
              Composition 0.0188 sec
           CompositionAcc 0.0016 sec
          CompositionDist 0.0029 sec
                    CTree 0.0003 sec
                 Delannoy 0.0025 sec
             Divisibility 0.0010 sec
                DyckPaths 0.0023 sec
                   Euclid 0.0068 sec
                    Euler 0.0044 sec
                 Eulerian 0.0029 sec
                Eulerian2 0.0027 sec
                EulerianB 0.0041 sec
           EulerianZigZag 0.3919 sec
                 EulerSec 0.0026 sec
                 EulerTan 0.0023 sec
           EytzingerOrder 0.0028 sec
            EytzingerPerm 0.0018 sec
              FallingFact 0.0012 sec
                FiboLucas 0.0012 sec
             FiboLucasInv 0.0012 sec
             FiboLucasRev 0.0008 sec
                Fibonacci 0.0014 sec
                   Fubini 0.0063 sec
              FussCatalan 0.0010 sec
                  Gaussq2 0.0037 sec
                 Genocchi 0.0032 sec
                 Harmonic 0.0018 sec
                 HermiteE 0.0027 sec
                 HermiteH 0.0019 sec
            HyperHarmonic 0.0018 sec
               Jacobsthal 0.0022 sec
                   Kekule 0.0045 sec
            LabeledGraphs 0.0245 sec
                 Laguerre 0.0024 sec
                      Lah 0.0096 sec
                   Lehmer 0.2257 sec
                  Leibniz 0.0018 sec
             LeibnizTable 0.0008 sec
                    Levin 0.0025 sec
                  Lozanic 0.0016 sec
                    Lucas 0.0011 sec
                LucasPoly 0.0015 sec
                  Moebius 0.0020 sec
                 Monotone 0.0052 sec
                  Motzkin 0.0061 sec
              MotzkinPoly 0.0018 sec
                 Narayana 0.0050 sec
                 Naturals 0.0011 sec
               Nicomachus 0.0014 sec
                   NimSum 0.0007 sec
                      One 0.0003 sec
                 Ordinals 0.0004 sec
             OrderedCycle 0.0035 sec
                  Parades 0.0693 sec
                Partition 0.0093 sec
             PartitionAcc 0.0008 sec
            PartitionDist 0.0026 sec
        PartitionDistSize 0.3128 sec
                   Pascal 0.0011 sec
             PolyaTreeAcc 0.4634 sec
                Polygonal 0.0013 sec
              PowLaguerre 0.0031 sec
               Rencontres 0.0026 sec
               RisingFact 0.0018 sec
               RootedTree 0.0012 sec
                Schroeder 0.0020 sec
               SchroederL 0.0023 sec
               SchroederP 0.0042 sec
                   Seidel 0.0020 sec
              SeidelBoust 0.0005 sec
               Sierpinski 0.0019 sec
            StirlingCycle 0.0025 sec
             StirlingCyc2 0.0012 sec
             StirlingCycB 0.0033 sec
              StirlingSet 0.0036 sec
             StirlingSet2 0.0057 sec
             StirlingSetB 0.0036 sec
                Sylvester 0.1552 sec
             TernaryTrees 0.0012 sec
                  WardSet 0.0031 sec
                WardCycle 0.0026 sec
                Worpitzky 0.0025 sec

                  103 tables tested!
                  
# List of OEIS A-numbers implemented.

['A000012', 'A001263', 'A001497', 'A001498', 'A002260', 'A002262', 'A004248', 'A004736', 'A008275', 'A008276', 'A008277', 'A008278', 'A008279', 'A008284', 'A008288', 'A008290', 'A008292', 'A008297', 'A008836', 'A009766', 'A009998', 'A014077', 'A019538', 'A021009', 'A021010', 'A025581', 'A026300', 'A027555', 'A028246', 'A028338', 'A033877', 'A038207', 'A039598', 'A039599', 'A039683', 'A039757', 'A039758', 'A046716', 'A048594', 'A048993', 'A048994', 'A049310', 'A050155', 'A051129', 'A051731', 'A052173', 'A053119', 'A053121', 'A053122', 'A053440', 'A054525', 'A054654', 'A055137', 'A056857', 'A056860', 'A058398', 'A059297', 'A059298', 'A059481', 'A061356', 'A063007', 'A064189', 'A066667', 'A068424', 'A072233', 'A075181', 'A075263', 'A080245', 'A080247', 'A080417', 'A081658', 'A089231', 'A090181', 'A090582', 'A094587', 'A094638', 'A094816', 'A096713', 'A098474', 'A098825', 'A104556', 'A104684', 'A105278', 'A106465', 'A106470', 'A106579', 'A106800', 'A109692', 'A111596', 'A112552', 'A112554', 'A113704', 'A119879', 'A122538', 'A122848', 'A122850', 'A123125', 'A124644', 'A128899', 'A128908', 'A130534', 'A130850', 'A131198', 'A131689', 'A132062', 'A132393', 'A137452', 'A139526', 'A144084', 'A151511', 'A151512', 'A153641', 'A154959', 'A163626', 'A168561', 'A173018', 'A173333', 'A181511', 'A213735', 'A225479', 'A271703', 'A278075', 'A285072', 'A322378', 'A363914']

"""